#!/bin/sh

DB_NAT_PORTFW_PUBLIC="1234-5678"
DB_NAT_PORTFW_INTERNAL="123400-567800"
#OIFS="$IFS"
IFS="-"
read -a PUBLIC_LIST <<< "${DB_NAT_PORTFW_PUBLIC}"
read -a INTERNAL <<< "${DB_NAT_PORTFW_INTERNAL}"
# IFS="$OIFS"

DB_NAT_PORTFW_PROTOCOLS="tcp/udp"
#OIFS="$IFS"
IFS="/"
for DB_NAT_PORTFW_PROTOCOL in $DB_NAT_PORTFW_PROTOCOLS; do
    IPTBL_FILTER_RULES+="-A FORWARD -d ${DB_NAT_PORTFW_IP}/32 -p ${DB_NAT_PORTFW_PROTOCOL} -m ${DB_NAT_PORTFW_PROTOCOL} --dport ${INTERNAL[0]}:${INTERNAL[1]} -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT"
    IPTBL_FILTER_RULES+=$'\n'
    IPTBL_NAT_RULES+="-A PREROUTING -i ${MLB_IFACE} -p ${DB_NAT_PORTFW_PROTOCOL} -m ${DB_NAT_PORTFW_PROTOCOL} --dport ${PUBLIC_LIST[0]}:${PUBLIC_LIST[1]} -j DNAT --to-destination ${DB_NAT_PORTFW_IP}:${INTERNAL[0]}-${INTERNAL[1]}"
    IPTBL_NAT_RULES+=$'\n'
done
IFS="$OIFS"

echo "$IPTBL_FILTER_RULES"
echo "$IPTBL_NAT_RULES"
